### ISSUE TITLE
Setup readthedocs

### ISSUE THREAD

**Issue by 73VW** [73VW/Publishing-to-PyPI-with-pbr-and-Travis#1]
The title says it all. Setup readthedocs for this project.

As the readme is pretty long, it would be great to be able to read it on readthedocs.

https://readthedocs.org/

**Comment by krishnaprasanthg** [comment]
i'll work on this

**Comment by 73VW** [comment]
@krishnaprasanthg Thanks!
We will add some more translations so if you could find a way to have multiple language for this too this could be nice. Thanks in advance

**Comment by 73VW** [comment]
See https://docs.readthedocs.io/en/latest/localization.html

**Comment by krishnaprasanthg** [comment]
@73VW Okay i'll have a look into that

**Comment by 73VW** [comment]
Thanks

**Comment by krishnaprasanthg** [comment]
let me know once you got set the read the docs account. the project name gets truncated, so need to shorten the name.. also need to adapt the README.md file

**Comment by 73VW** [comment]
https://automate-your-publishing-to-pypi-with-pbr-and-travis.readthedocs.io/en/latest/
Nothing gets truncated 🤔

**Comment by 73VW** [comment]
How do I put translations now?
I am not sure to understand correctly
Someone made a Russian translation. How do I integrate it?
